# Generated by Django 6.0.2 on 2026-03-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('departemen', models.CharField(max_length=50)),
                ('posisi', models.CharField(max_length=50)),
                ('tgl_masuk', models.DateField()),
                ('gaji', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
