# Generated by Django 6.0.2 on 2026-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('tgl_lahir', models.DateField()),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('no_hp', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('kelurahan', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('kabupaten_kota', models.CharField(max_length=50)),
                ('provinsi', models.CharField(max_length=50)),
                ('kode_pos', models.CharField(max_length=10)),
                ('no_ktp', models.CharField(max_length=16, unique=True)),
                ('no_kk', models.CharField(max_length=16)),
                ('status_kawin', models.CharField(choices=[('TK', 'Tidak Kawin'), ('K0', 'Kawin 0'), ('K1', 'Kawin 1'), ('K2', 'Kawin 2'), ('K3', 'Kawin 3')], max_length=20)),
                ('tanggungan', models.IntegerField(default=0)),
                ('agama', models.CharField(max_length=20)),
                ('tinggi_badan', models.IntegerField(help_text='dalam cm')),
                ('berat_badan', models.IntegerField(help_text='dalam kg')),
                ('gol_darah', models.CharField(blank=True, max_length=2, null=True)),
                ('pendidikan', models.CharField(max_length=20)),
                ('tgl_rekrut', models.DateField()),
                ('status_karyawan', models.CharField(choices=[('Tetap', 'Tetap'), ('Kontrak', 'Kontrak'), ('Probation', 'Probation'), ('Outsourcing', 'Outsourcing')], max_length=20)),
                ('tgl_kartetap', models.DateField(blank=True, null=True)),
                ('dept', models.CharField(max_length=50)),
                ('jabatan', models.CharField(max_length=50)),
                ('posisi_karyawan', models.CharField(max_length=50)),
                ('kontrak_ke', models.IntegerField(default=1)),
                ('kontrak_berakhir', models.DateField(blank=True, null=True)),
                ('kode_gaji', models.CharField(blank=True, max_length=20, null=True)),
                ('no_rek_bank', models.CharField(max_length=20)),
                ('kode_bank', models.CharField(max_length=10)),
                ('nama_bank', models.CharField(max_length=50)),
                ('bpjs_tk', models.BooleanField(default=False)),
                ('bpjs_tk_no', models.CharField(blank=True, max_length=20, null=True)),
                ('bpjs_kes', models.BooleanField(default=False)),
                ('bpjs_kes_no', models.CharField(blank=True, max_length=20, null=True)),
                ('status_ptkp', models.CharField(blank=True, max_length=20, null=True)),
                ('no_npwp', models.CharField(blank=True, max_length=20, null=True)),
                ('status_pajak', models.CharField(blank=True, max_length=20, null=True)),
                ('faskes', models.CharField(blank=True, max_length=50, null=True)),
                ('placement', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_karyawan/')),
                ('tgl_out', models.DateField(blank=True, null=True)),
                ('status_kerja', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
