# Generated by Django 6.0.2 on 2026-03-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='nip',
            new_name='nik',
        ),
    ]
