# Generated by Django 6.0.2 on 2026-03-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_employee_kabupaten_kota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tgl_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
