# Generated by Django 6.0.2 on 2026-03-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_employee_tgl_lahir'),
        ('hr', '0006_remove_no_ktp_unique'),
    ]

    operations = [
    ]
